### PR TITLE
fix(nextjs): update deps and fix example

### PR DESCRIPTION
**Pull request by kyletsang**
This PR updates all deps and fixes several issues with the latest version of `nextjs-mf`.  I've also modified the scripts so they can also be run on Windows.

### CODE REVIEW

**Comment by valorkin** [comment]
Hello @kyletsang ,

Thank you so much for submitting a pull request.
I would like to suggest that we create two folders, one for Next.js 12 and one for Next.js 13, 
in order to maintain backwards compatibility in this repository.

**Comment by kyletsang** [comment]
Hey @valorkin, sounds good.  Did you want me to leave this PR with v13 and I'll create a separate one for v12 or did you want them both in the same PR?

**Comment by kyletsang** [comment]
Added it as a separate PR since it's easier to track: https://github.com/module-federation/module-federation-examples/pull/2571

**Comment by valorkin** [comment]
awesome, thank you!
please rename folder in this PR to nextjs-13
and I will ask QA to test locally and approve for merge ;)

**Comment by valorkin** [comment]
cc @VladyslavZinchenko

**Comment by VladyslavZinchenko** [comment]
cc @valorkin Approved

**Review by VladyslavZinchenko — APPROVED** [review]

**Comment by kyletsang** [comment]
Folder has been renamed and readme updated

**Review by valorkin — APPROVED** [review]

**Pull request merged**
