### PR TITLE
add webpack4

### PR DESCRIPTION
**Pull request by zhangHongEn**
Module Federation is implemented in webpack4. The current example demonstrates that MF of webpack4 and webpack5 call each other

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
Would you consider moving the webpack 4 package to the module federation organization and shipping it under the MF namespace 

you’d be added as a maintainer/admin of the repo and all credit would remain yours. It would just be part of the official MF umbrella, get more traffic, and make it easy for users to find

**Comment by zhangHongEn** [comment]
> Would you consider moving the webpack 4 package to the module federation organization and shipping it under the MF namespace
> 
> you’d be added as a maintainer/admin of the repo and all credit would remain yours. It would just be part of the official MF umbrella, get more traffic, and make it easy for users to find

Yes, I will continue to maintain this library

Do I need to make preparations? I can directly operate in "github" and "npm" or how to cooperate

**Comment by ScriptedAlchemy** [comment]
Ill cut a repo, DM me on twitter if you have it or here's my slack link

https://join.slack.com/t/scriptedalchemy/shared_invite/zt-1ffts0ws7-Xkjiw7yXTvd6ouwnlQxx2w

**Comment by zhangHongEn** [comment]
> Ill cut a repo, DM me on twitter if you have it or here's my slack link
> 
> https://join.slack.com/t/scriptedalchemy/shared_invite/zt-1ffts0ws7-Xkjiw7yXTvd6ouwnlQxx2w

I have joined "slack"

**Pull request closed without merging**
