### PR TITLE
Upgrade vue cli service

### LINKED ISSUE #1896: Cannot find module 'webpack/lib/rules/DescriptionDataMatcherRulePlugin'
I'm trying to build the vue-cli demo without success

Could it be because I'm using an unsupported version of node/npm ?

```
$ node -v
v17.6.0
$ npm -v
8.5.1
```

```
yarn install # ok
yarn build # fails
```

```
ERROR  Error: Cannot find module 'webpack/lib/rules/DescriptionDataMatcherRulePlugin'
        Require stack:
        - /module-federation-examples/vue-cli/consumer/node_modules/@vue/cli-service/node_modules/@vue/vue-loader-v15/lib/plugin-webpack5.js
        - /module-federation-examples/vue-cli/consumer/node_modules/@vue/cli-service/node_modules/@vue/vue-loader-v15/lib/plugin.js
        - /module-federation-examples/vue-cli/consumer/node_modules/@vue/cli-service/node_modules/@vue/vue-loader-v15/lib/index.js
        - /module-federation-examples/vue-cli/consumer/node_modules/@vue/cli-service/lib/config/base.js
        - /module-federation-examples/vue-cli/consumer/node_modules/@vue/cli-service/lib/Service.js
        - /module-federation-examples/vue-cli/consumer/node_modules/@vue/cli-service/bin/vue-cli-service.js
```

Indeed the file `DescriptionDataMatcherRulePlugin` is not found inside `node_modules/webpack/lib/rules/`

### PR DESCRIPTION
**Pull request by kentahama**
Fix #1896.

### CODE REVIEW

**Comment by 695648896** [comment]
i add library: {type: 'var'} in my vue.config.js. but it doesn't work 
but if i add splitChunks: false  it work 
do you know why?

**Comment by ScriptedAlchemy** [comment]
Looks good to me, is this ready to merge or still draft?

**Review by ScriptedAlchemy — APPROVED** [review]

**Comment by kentahama** [comment]
This works with doing `yarn install` in every subdirectory (vue-cli/consumer, vue-cli/core, vue-cli/other), but does not work with doing in root directory. I am trying to do update root's `yarn.lock` but not going well. Is it okay to merge?

**Comment by ScriptedAlchemy** [comment]
Try adding no hoist or checking if the project is listed on the workspace. If it’s not working then just remove it from the workspace and create a little setup script that cd into each folder and runs the install. Then update the readme for that example. I have a few apps that require a sub install and are not part of the monorepo base yarn install

**Pull request merged**
