### PR TITLE
SSR Loadable example

### PR DESCRIPTION
**Pull request by 7rulnik**
I tried to lunch it but no luck.

With target `async-node` I'm getting `TypeError: Cannot read property 'call' of undefined` on the server side. But `node` it works.

There are some problems with rehydration, but I believe it's because of wrong stats.
I think it's a good idea to try `async-node` in a different project without module federation.

UPD: changed target to async-node in this example https://github.com/gregberge/loadable-components/tree/master/examples/server-side-rendering and everything is alright.

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
async node is helpful with streamed code. but node is probably the best solutoin

**Comment by 7rulnik** [comment]
@ScriptedAlchemy do you mean if we load some chunks on demand so need to use node-async? And if all chunks are static so we can go with node?

**Comment by ScriptedAlchemy** [comment]
Not quite. If I’m streaming module right out of s3 then node-async is best. But node should work in your use case

**Comment by ScriptedAlchemy** [comment]
If this is functional. Can we merge?

**Comment by 7rulnik** [comment]
Nope, I changed target to `node`, but async chunk from website2 doesn't work during SSR website1.

**Comment by 7rulnik** [comment]
Fixed it by setting loadable as shared. Seems that it has some context things.

Still need to figure out how to deal with rehydration. I have some thoughts, will try to do it

**Comment by 7rulnik** [comment]
bootstrap.js is not a thing anymore, isn't it?

**Comment by 7rulnik** [comment]
Well, SSR works perfectly but I'm getting this error in main.js on client:

module with id 2403 doesn't exist.
image


2403 stands for module from website2: `website2/SomeComponent`
```js
 /* harmony import */ var website2_SomeComponent__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! website2/SomeComponent */ 2403);
```
and it's only one mention in both bundles.

With bootstrap.js all was working but it was impossible to predict which files will be needed so it had loaded two js files (from website1 and website2) after startup and I didn't find any connections in stats files.

Am I missing something?

**Comment by ScriptedAlchemy** [comment]
Looks like the js file is missing? The remote entry in the html? Otherwise add bootstrap back and test again. It’s removed for most cases but SSR likely still would be good to use bootstrap. Compare with master

**Comment by 7rulnik** [comment]
Yep, the remote is here. It works with bootstrap import in the host and normal entry in remote so I will leave it like that. Why is it good to use bootstrap though?

With this setup I'm getting 2 chunks via jsonp:

image

197 contains `website1/src/bootstrap.js`
522 contains `website2/src/components/SomeComponent.js`

So they are necessary parts. Main question: how to predict that these chunks will be needed on client?

Loadable uses `namedChunkGroups` and `assets` from stats. This is stats file for website1 (see comment):

```json5
"namedChunkGroups": {
    "main": {
      "name": "main",
      "chunks": [
        179
      ],
      "assets": [
        "main.1d6d0191b0eb01a2689e.js"
        /* I belive there should be 197.dd5598a4dea5d61081a6.js*/
      ],
      "auxiliaryAssets": [
        "main.1d6d0191b0eb01a2689e.js.map"
      ],
      "children": {},
      "childAssets": {},
      "isOverSizeLimit": false
    },
    "Async": {
      "name": "Async",
      "chunks": [
        648
      ],
      "assets": [
        "Async.708b8060e1f55bbe4db0.js"
      ],
      "auxiliaryAssets": [
        "Async.708b8060e1f55bbe4db0.js.map"
      ],
      "children": {},
      "childAssets": {},
      "isOverSizeLimit": false
    }
  }
```

**Comment by ScriptedAlchemy** [comment]
You’d need to federate the loadable stats as well so the host is aware

**Comment by 7rulnik** [comment]
But I'm already doing it https://github.com/module-federation/module-federation-examples/pull/19/files#diff-6ea55ab73968e6a2483ffca63cd90c1bR62

**Comment by ScriptedAlchemy** [comment]
I’ll take a look :)

**Comment by 7rulnik** [comment]
BTW I figured out why async-node breaks with loadable components. It works with chunks in sync way.
https://github.com/gregberge/loadable-components/blob/338bf555adc68986b12c8dd4e304875425119ca2/packages/component/src/createLoadable.js#L75

@theKashey any ideas about how we can solve it?

**Comment by theKashey** [comment]
Hey guys, long time no see 😁
This - https://github.com/gregberge/loadable-components/pull/568 - might help with the problem. @7rulnik - could you please try it.

Meanwhile - `loadable` overrides webpack's `jsonp_callback` for living, and is it working for already bundled remote as well?

**Comment by 7rulnik** [comment]
@theKashey I tried but got the same error.
`jsonp_callback` works fine, yes.
 
I want to check the example in loadable repo. Maybe I was wrong and the problem exists there too.

**Comment by 7rulnik** [comment]
I can confirm that example in loadable repo fails too. I believe it's better to track in loadable repo so I will file the issue and will add the example

**Review by dylanjeffers — COMMENTED** [review]
This looks awesome. Question on the merged stats file. It seems like website1 is referencing website2's stats directly from source, is that correct?

**Comment by 7rulnik** [comment]
@SapienTech you can import/fetch it from any  source, for example from S3

**Comment by prateekr1** [comment]
@7rulnik there is already a issue filed in loadable repo for this issue

https://github.com/gregberge/loadable-components/issues/558



> I can confirm that example in loadable repo fails too. I believe it's better to track in loadable repo so I will file the issue and will add the example

:+1:

**Comment by theKashey** [comment]
[server-side-rendering](https://github.com/gregberge/loadable-components/tree/master/examples/server-side-rendering)? It fails due to moment-js "default export" transformation, which is a bit different case.

**Comment by 7rulnik** [comment]
@theKashey I tried without moment too. Same error.

**Comment by theKashey** [comment]
Ok, but we are talking about the same example. I was running it with changes in the PR I've mentioned above just a few days ago, and it was working (except loadable.lib).

**Comment by prateekr1** [comment]
@7rulnik 

> I can confirm that example in loadable repo fails too. I believe it's better to track in loadable repo so I will file the issue and will add the example

can you specify steps to reproduce it in `example` of `loadable repo`.

**Comment by 7rulnik** [comment]
I created PR with repro failing with `async-node` target so let's track this problem in loadable-components repo.

https://github.com/gregberge/loadable-components/pull/575

**Comment by theKashey** [comment]
@7rulnik - I'll borrow your example for imported-component as well.

**Comment by ScriptedAlchemy** [comment]
Async node uses fs+vm vs node which uses require

**Comment by 7rulnik** [comment]
@ScriptedAlchemy so we [need these assets](https://github.com/module-federation/module-federation-examples/pull/19#issuecomment-626704241) in webpack stats or in separate federation stats. I want to contribute it, but maybe you could point me where I should start?

**Comment by theKashey** [comment]
@7rulnik - please check this PR - https://github.com/gregberge/loadable-components/pull/573 - might be it changes something in a way you need it.

**Comment by 7rulnik** [comment]
Why did you close it? @ScriptedAlchemy

**Comment by ScriptedAlchemy** [comment]
Rewrite git history

**Comment by ScriptedAlchemy** [comment]
can you branch off master, then merge this back into a new branch that's fresh from baster

**Pull request closed without merging**
