### PR TITLE
Next medusa delegates

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**

### CODE REVIEW

**Comment by VladyslavZinchenko** [comment]
image_720
 I have this error on my Windows machine when I try to build the app
The issue is not reprodeced on Linux and macOs

**Comment by ScriptedAlchemy** [comment]
Ahh windows paths. Okay I know what to do

**Comment by ScriptedAlchemy** [comment]
@VladyslavZinchenko is this version any better? ` 2.8.0-beta.4`

**Comment by VladyslavZinchenko** [comment]
@ScriptedAlchemy The issue is still reproduced 
image

**Comment by ScriptedAlchemy** [comment]
@VladyslavZinchenko how about 2.8.0-beta.5?

**Comment by VladyslavZinchenko** [comment]
@ScriptedAlchemy Have the same error

**Pull request closed without merging**
