### PR TITLE
Dynamic remote not initialising bug reproduced

### PR DESCRIPTION
**Pull request by saravanan10393**

### CODE REVIEW

**Review by ScriptedAlchemy — APPROVED** [review]
Much better. Ive just patched next.js and wrapped the init inside a try catch so it wont re-attach over and over. This is the more correct way to do it.

**Comment by saravanan10393** [comment]
@ScriptedAlchemy this pr is to demonstrate the bug mentioned  here https://twitter.com/sara_vananr/status/1316389885805092864?s=19, for which I have asked help for.  

Pls Run the dynamic system host example once to see the error I have been talking about.

**Comment by ScriptedAlchemy** [comment]
Ohhh oops

**Comment by saravanan10393** [comment]
Yes @ScriptedAlchemy , If you click on the App3Homepage button, error will come. Can you help me to fix and understand why this issue is coming.

**Pull request merged**
