### PR TITLE
MF Examples: Improvements to dynamic-system-host

### PR DESCRIPTION
**Pull request by ssuf**
- Makes the example slightly more "realistic"  
  
  
_Potential To Do_:
- Add remote import-map for fully dynamic runtime imports

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
The script injection should probably use something like this. https://gist.github.com/ScriptedAlchemy/3a24008ef60adc47fad1af7d3299a063

**Comment by ssuf** [comment]
Updated @ScriptedAlchemy 😅

**Comment by hnguyenec** [comment]
Can we have the example using the latest module federation to dynamically load remote mfe apps (eg: using init({json})) implemented in nextjs 14

Thanks

**Comment by ScriptedAlchemy** [comment]
Next currently doesn't support the manifest protocol

**Pull request merged**
