### PR TITLE
Add typescript-react-monorepo example

### PR DESCRIPTION
**Pull request by MostafaRastegar**

### CODE REVIEW

**Comment by MostafaRastegar** [comment]
@PeaceDate 
hi.
why fail forked_master_status?!

**Comment by ScriptedAlchemy** [comment]
might be due to very old examples that still use 'submodule.proprietary-tools.path' repo?

Im not sure ifs related but i do have a git repo called propriatery tools that was used as the npm install point for some very old examples - those can likely be removed if its causing an issue

**Comment by ScriptedAlchemy** [comment]
@MostafaRastegar try rebasing, i removed the references to proprietary tools, it was a old example anyways

**Comment by MostafaRastegar** [comment]
@ScriptedAlchemy 
I did not get it.
What exactly should I do now?

**Comment by PeaceDate** [comment]
@MostafaRastegar 
To pass this check you need simply update your fork master branch to be up to date with the master branch of the main repo. And of course rebase your feature branch. 

This made for that cases when you can rewrite smth only because you create your feature branch from extremely old master.

Try to always keep your fork up to date :)

**Pull request merged**
