### PR TITLE
Add Angular Universal example

### PR DESCRIPTION
**Pull request by newvladimirov**

### CODE REVIEW

**Review by ScriptedAlchemy — APPROVED** [review]
hardly understand a single line, but if its good lets merge

**Comment by ScriptedAlchemy** [comment]
@newvladimirov can you resolve the conflict, then we can merge

**Comment by newvladimirov** [comment]
@ScriptedAlchemy done.

**Comment by ScriptedAlchemy** [comment]
Appreciate your time and effort exploring module Federation

**Comment by ScriptedAlchemy** [comment]
@newvladimirov some are experiencing this image

**Comment by newvladimirov** [comment]
@ScriptedAlchemy Oh, It's my bad, gonna fix it in a couple of hours.

**Pull request merged**
