### PR TITLE
add relatively complete case in react

### PR DESCRIPTION
**Pull request by anderlaw**
Hi, I've tried and studied the Webpack Module Federation feature recently, I was working with React and it was difficult to get a complete case that fit my needs, with several weeks of frustrating and searching, I created a relatively complete example project.

In order to help people like me, save their time, I want to make a PR, merge this example into this repository.

this example including:`remote-app`,`remote-host-app`,`host-app`, I also wrote several exposed components .

Thanks.

Project screenshots here :
image
image

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
@anderlaw this is great - is there any chance you can translate the remaining non-english text in the readme and example?

**Comment by anderlaw** [comment]
Sure. there are two parts or files with no-English text:
- `READEME.md`. It is a mix of English and Chinese language version, they express the same thing
- `component-app`'s local file

For the second, I will definitely modify that; 
What about the first one? because I wanna make sure both Chinese and English speaking people can understand it, do you have any suggestion? thanks

**Comment by ScriptedAlchemy** [comment]
goo point on supporting multi lamguage, perhaps, if you're displaying anything meaningful in CZ, just translate the text en EN below so users can read either or? I've never dealt with multi-lang readmes but lets give it a practical, low effort attempt - it would be great to have more foreign language docs and articles for sure!

**Comment by anderlaw** [comment]
Hi Zack, I just upload commits. and keep two `README.md` files, one for EN, one for CN.
also, add links to each other

**Comment by multsentender** [comment]
@anderlaw 
Hi, I'm interested in your case. Tell me, is it possible to share DevPackages that are not directly imported into the file (for example, @types/react)

**Pull request merged**
