### PR TITLE
webpack eager loading error fix

### PR DESCRIPTION
**Pull request by sathyarajagopal**
dependencies were loaded multiple times in webpack mod fed api shared section. This contributes to eager loading events error. I have commented out the deps to fix this.

### CODE REVIEW

**Review by ScriptedAlchemy — APPROVED** [review]
Ahhh that'll do it!

**Comment by ESoch** [comment]
@sathyarajagopal, I believe this will break the UI. It looks like multiple instances of `@material-ui/core` are now getting loaded causing funkiness with button styling and the navigation menu/header.

Add this below as one of the shared dependencies seems to fix this. 

```
  '@material-ui/core': {
    singleton: true,
    requiredVersion: deps['@material-ui/core'],
  }
 ```

CC: @ScriptedAlchemy

**Comment by sathyarajagopal** [comment]
> 4a88537

Yup. That will do it.

**Comment by ScriptedAlchemy** [comment]
Send a pr

**Comment by ESoch** [comment]
I am currently waiting for my plane so I was able to get to it. I've opened a PR here: https://github.com/module-federation/module-federation-examples/pull/2026

**Pull request merged**
