### PR TITLE
nextjs updates

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**
Fixes nextjs and federation on the client side

### CODE REVIEW

**Comment by crutch12** [comment]
```
ReferenceError: __non_webpack_require__ is not defined
    at patchSharing (C:\Users\criit\Documents\Bitbucket\module-federation-examples\nextjs\next1\node_modules\@module-federation\nextjs-mf\patchSharing.js:6:34)
    at MyDocument.render (C:\Users\criit\Documents\Bitbucket\module-federation-examples\nextjs\next1\.next\server\pages\_document.js:1281:8)
```

**Comment by ScriptedAlchemy** [comment]
fixed

**Comment by crutch12** [comment]
@ScriptedAlchemy as I can see it will be fixed by https://github.com/module-federation/nextjs-mf/pull/24

Now I still have the same error

**Comment by markhughes** [comment]
@crutch12 your fix works! https://github.com/module-federation/nextjs-mf/commit/85f2e0c0e2f0de6af6ff156664a185e40eff1f5e

@ScriptedAlchemy we need to deploy to npmjs https://www.npmjs.com/package/@module-federation/nextjs-mf as the current build wont work for anyone.

**Pull request merged**
