### PR TITLE
 Next.js sidecar with hooks - webpack@5.0.0-beta.22

### PR DESCRIPTION
**Pull request by Kinbaum**
Hi @ScriptedAlchemy 

I have refactored the Next.js sidecar example to work with the latest webpack 5 beta (22).

### CODE REVIEW

**Comment by Kinbaum** [comment]
Hey @ScriptedAlchemy I wanted to point out that I was seeing some weird behavior, possible tied to HMR.
The issue I am seeing on beta.22 is that in the dog-admin app (webpack 5), when consuming a remote, I run into an error that says `version.forEach is not a function`. My understanding was that version was changed from an array to a `string | boolean`. Trying to set is as an array in the shared config throws a compilation error for not following the schema.

A weird thing I noticed is that if I have all of the apps running (host, dog-admin, sidecar), the Next.js host works fine. The dog-admin app will throw the error, but as soon as I modify its `index.html` and save file, then everything seems to resolve. Thoughts?

**Comment by ScriptedAlchemy** [comment]
Ensure you've upgraded webpack on all your apps. Make sure to use beta 22. I was run into this issue on my examples repo and am busy performing a sweeping update to latest webpack beta. Beta 21 has a bug 🐛

**Comment by ScriptedAlchemy** [comment]
I'll merge this in and then review and fix it. I'm already going folder by folder. Likely yarn resolution error higher up in the chain

**Comment by Kinbaum** [comment]
Sounds good. Thanks

**Comment by ScriptedAlchemy** [comment]
Merged in and patched under my open PR

**Pull request merged**
