### PR TITLE
Federated page routing with nextJS

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**

### CODE REVIEW

**Comment by bwcgn** [comment]
@ScriptedAlchemy are there still open issues with this approach?

**Comment by ScriptedAlchemy** [comment]
Yeah, I'm working on it at internally at the company. We have it working, but there's some quirks we are still working out before I'll cut a new branch and show it publicly

**Comment by ScriptedAlchemy** [comment]
Plugin has been redesigned and implementation has been drafed in a new PR #892

**Comment by ScriptedAlchemy** [comment]
closing in favor of #892

**Pull request closed without merging**
