### PR TITLE
Next.js sidecar with hooks

### PR DESCRIPTION
**Pull request by Kinbaum**
This example addresses the issue with using hooks in federated components and consuming them in a Next.js application. There is no need to mark React or ReactDOM as external with this example.

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
Are you also able to fix the externalized react issue on the original sidecar example?

**Comment by Kinbaum** [comment]
Yes for sure. Would you like me to open another PR for that one, or replace this one with that change?

**Comment by ScriptedAlchemy** [comment]
Could the two be merged? showcase hooks and class-based components? It also reduces my maintenance burden as the examples are getting quite long haha

**Comment by Kinbaum** [comment]
Yeah no problem. I'll combine the two examples and submit them as one in this PR. Thanks

**Comment by ScriptedAlchemy** [comment]
Appreciate it!

**Comment by Kinbaum** [comment]
@ScriptedAlchemy I have consolidated the examples. Ready for you to check it out.

**Comment by ScriptedAlchemy** [comment]
Will check it out! 🙏

**Comment by Kinbaum** [comment]
@ScriptedAlchemy Something got messed up. I'm gonna close this and reopen a new one that's cleaner.

**Comment by ScriptedAlchemy** [comment]
thanks

**Comment by Ruchika-saini** [comment]
@Kinbaum @ScriptedAlchemy 
Is this issue fixed? As I am still facing the issue with hooks. 
I am using this package @module-federation/nextjs-mf@**2.3.1** in Next JS application to federate a page. But whenever I have React hooks in remote module, I am getting this error "Uncaught Error: Invalid hook call".
Even I have this configuration as well

_shared: {
                'styled-jsx': {
                requiredVersion: false,
                singleton: true,
                eager: true,
              },
              react: {
                singleton: true,
                eager: true,
                requiredVersion: false,
              },
              'react-dom': {
                singleton: true,
                eager: true,
                requiredVersion: false,
              },
            },_

Please help on this issue and clarify if this fix is available in **v2.3.1** of @module-federation/nextjs-mf (the latest that is available on the public npm registry).

**Comment by ScriptedAlchemy** [comment]
@Ruchika-saini you need the commercial version from privjs registry. Not npm

**Pull request closed without merging**
